<MainWidget>:
    BoxLayout:
        orientation: 'horizontal'
        size: app.width, app.height

        BoxLayout:

            Label:
                id: the_number
                text: "1"

        BoxLayout:
            orientation: 'vertical'
            padding: 2

            Button:
                id: count_up
                text: "+"

            Button:
                id: count_down
                text: "-"